Description: First homework

Parameters:
  KeyName:
    Description: EC2 Instance SSH Key
    Type: AWS::EC2::KeyPair::KeyName

  InstanceType:
    Description: EC2 Instance config
    Type: String
    Default: t2.medium
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      ImageId: ami-00ee4df451840fa9d
      InstanceType:
        Ref: InstanceType

Outputs:
  PublicIp:
    Description: RC2 Instance pubic IP
    Value: !GetAtt EC2Instance.PublicIp